spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wnsql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: wn
    password: 1
    driver-class-name: com.mysql.jdbc.Driver