spring:
    datasource:
      url: jdbc:mysql://localhost:3306/wnsql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 1
      driver-class-name: com.mysql.jdbc.Driver
      wwn:
        jdbc-url: jdbc:mysql://localhost:3306/wnsql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: wwn
        password: 1
        driver-class-name: com.mysql.jdbc.Driver
      wn:
        jdbc-url: jdbc:mysql://localhost:3306/wnsql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: wn
        password: 1
        driver-class-name: com.mysql.jdbc.Driver
