spring:
  ## thymeleaf ƒ£∞Â≈‰÷√–≈œ¢
  thymeleaf:
    cache: true
    check-template-location: true
 ##   content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: